let FG_COLOR = "#FFFFFF"
let BG_COLOR = "#FFFFFF"
let STROKE_COLOR = "#000000"

let DECORATION_COLOR = FG_COLOR
let DECORATION_DOT_COLOR = "#000000"

let TRUCHET_COLOR = FG_COLOR
let TRUCHET_FEATHER_COLOR = BG_COLOR
let TRUCHET_FEATHER_DOT_COLOR = FG_COLOR
let TRUCHET_ZIGZAG_COLOR = BG_COLOR
let TRUCHET_ZIGZAG_DOTS_COLOR = BG_COLOR
let TRUCHET_CREST_SHORT_COLOR = BG_COLOR
let TRUCHET_CREST_LONG_COLOR = BG_COLOR
let TRUCHET_ARC_COLOR = BG_COLOR

let DINO_COLOR = FG_COLOR
let DINO_EYE_COLOR = BG_COLOR
let DINO_NOSE_COLOR = BG_COLOR
let DINO_TOOTH_COLOR = FG_COLOR
let DINO_SCAR_COLOR = BG_COLOR
let DINO_TATTOO_COLOR = STROKE_COLOR

let HUMAN_COLOR = FG_COLOR
let HUMAN_EYE_COLOR = BG_COLOR
let HUMAN_IRIS_COLOR = FG_COLOR
let HUMAN_NOSE_COLOR = BG_COLOR
let HUMAN_MOUTH_COLOR = BG_COLOR
let HUMAN_TATTOO_COLOR = STROKE_COLOR

let SKULL_COLOR = FG_COLOR
let SKULL_EYE_COLOR = STROKE_COLOR
let SKULL_TUBE_COLOR = FG_COLOR
let SKULL_CROSS_COLOR = FG_COLOR
let SKULL_CUBE_COLOR = FG_COLOR
